server:
  address: 192.168.0.101
  port: 8080



spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop;MODE=MYSQL
    username: sa
    password: sa
    driver-class-name: org.h2.Driver

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  servlet:
    multipart:
#      location: /Users/sinminseok12/Desktop/ohmimage
      max-file-size: 200MB
      max-request-size: 200MB

  jpa:

    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show-sql:true
        format_sql = true

logging.level:
  org.hirbernate.SQL: debug


jwt:
  header: Authorization
  secret: Z2ZkZmdkZmxrZ2pkbGZrZ2pzYXNkamtoYXNrZGphaHNka2fahgvfahvduyasdffjkhsgdfjkhasgfjkphaGRhc2Rhc2Rhc2Rhc2Rhc2ZhZmdzZAo=
  access-token-validity-in-seconds: 86400
